[all]
server2 ansible_host=192.168.1.122 private_ip=172.16.0.102
server3 ansible_host=192.168.1.123 private_ip=172.16.0.103
server4 ansible_host=192.168.1.124 private_ip=172.16.0.104
server5 ansible_host=192.168.1.125

[master]
server2

[slaves]
server3
server4

[db_servers:children]
master
slaves

[loadbalancer]
server5

[all:vars]
ansible_user=hasan
ansible_port=22
