[all]
server2 ansible_host=192.168.1.122
server3 ansible_host=192.168.1.123
server4 ansible_host=192.168.1.124
server5 ansible_host=192.168.1.125

[master]
server2

[slaves]
server3
server4

[db_servers:children]
master
slaves

[loadbalancer]
server5 ansible_host=192.168.1.125

[all:vars]
ansible_user=hasan
ansible_port=22
