---
- name: Install MariaDB, Galera and tools
  apt:
    name:
      - "{{ mariadb_server_package }}"
      - "{{ mariadb_client_package }}"
      - "{{ galera_package }}"
      - "{{ rsync_package }}"
      - "{{ socat_package }}"
    state: "{{ mariadb_package_state }}"
    update_cache: yes

- name: Copy Galera Config
  template:
    src: 50-server.cnf.j2
    dest: "{{ galera_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart mariadb

- name: Ensure mysql log directory exists
  file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: Ensure mysql directories ownership
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
  loop:
    - /var/lib/mysql
    - /var/log/mysql

- name: Ensure MariaDB started
  service:
    name: mariadb
    state: started
    enabled: true
